### ISSUE TITLE
Cannot disable "template-no-call-expression" rules.

### ISSUE THREAD

**Issue by Zarepheth** [mgechev/codelyzer#848] opened 2019-06-06 17:44 UTC
**Describe the bug**

`tslint` processes the `template-no-call-expression` rule even when it is set to `false` and also when a `tslint:disable:template-no-call-expression` comment is added to either the template (using an HTML comment) or the component's class file (using a TypeScript comment).

As a result, `tslint` spams me with `Call expressions are not allowed in templates except in output handlers`.

**Context and configuration**

Please share:
 - Which rule is causing the problem
    `template-no-call-expression`
 - What's the content of your `tsconfig.json`
``` json
{
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": false,
    "preserveWhiteSpace": false,
    "strictInjectionParameters": true,
    "strictMetadataEmit": true,
    "trace": true
  },
  "compileOnSave": false,
  "compilerOptions": {
    "allowJs": true,
    "alwaysStrict": true,
    "baseUrl": "Client",
    "checkJs": false,
    "declaration": false,
    "downlevelIteration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["dom", "dom.iterable", "es6"],
    "module": "es2015",
    "moduleResolution": "node",
    "newLine": "CRLF",
    "outDir": "dist/out-tsc",
    "pretty": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strict": true,
    "strictPropertyInitialization": false,
    "target": "es5"
  },
  "exclude": ["bin", "dist", "karma.conf.js", "node_modules", "obj", "protractor.conf.js", "wwwroot"],
  "include": ["Client"],
  "typeAcquisition": {
    "enable": true,
    "include": ["bootstrap", "jquery"]
  }
}
```
 - What's the content of `~/.codelyzer.js` (if applicable)
     no `.codelyzer.js` file.

**To Reproduce**

Not yet reproduced in a minimal project, but components use separate template files, in the same subdirectory as the component's class. Template contains method calls in some property bindings (for HTML elements, Angular directives, and child components) or in interpolations `{{ ... }}`. Where the bound properties are not annotated with `@Output()` in their declarations, tslint reports: `Call expressions are not allowed in templates except in output handlers` even when the rule should be turned off.

**Expected behavior**

I expect tslint with codelyzer to enforce all non-disabled rules, while ignoring and not reporting errors for rules that are disabled.

**Code**

In the code below, tsling with codelyzer reports an error at `isValueNoChoice(inputValue)`. If the rule were enabled, I would expect this error. When the rule is disabled, I do not.

``` html
<select class="form-control-sm px-1 "
  [ngClass]="valueControlCssClasses"
  [class.text-muted]="isValueNoChoice(inputValue)" [(ngModel)]="inputValue"   
  (change)="onValueChange($event)">
    <option class="text-muted" [value]="dropdownNoChoiceOption.value"
      *ngIf="dropdownNoChoiceOption">{{ dropdownNoChoiceOption.text }}</option>
    <option class="text-dark" *ngFor="let choice of dropdownChoices" [value]="choice.value || choice.text">{{ choice.text }}</option>
</select>
```

**Environment**

From `package.json`:
``` json
    "angular-tslint-rules": "^1.14.0",
    "codelyzer": "^4.5.0",
    "prettier": "^1.17.1",
    "tslint": "^5.16.0",
    "tslint-config-prettier": "^1.18.0",
    "tslint-plugin-prettier": "^2.0.1",
```

`ng --version` output: `6.9.0`

```
Angular CLI: 7.3.9
Node: 10.1.0
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0
```

Partial `tslint.json` file:
``` javascript
{
  "extends": ["angular-tslint-rules", "tslint-plugin-prettier" /*, "tslint-config-prettier" */],
  "rulesDirectory": ["node_modules/codelyzer"],
  "linterOptions": {
    "exclude": [
      "*.*proj",
      "*.config",
      "*.user",
      "**/.vs/**/*",
      "**/.vscode/**/*",
      "**/bin/**/*",
      "**/node_modules/**/*",
      "**/obj/**/*",
      "**/Properties/**/*",
      "**/wwwroot/**/*",
      "./desktop.ini",
      "./Client/polyfills.ts"
    ]
  },
  "jsRules": true,
  "rules": {
    "prettier": true,
    "no-unused-css": false,
    "prefer-inline-decorator": [false],
    "prefer-template": [false, "allow-single-concat"],
    "template-conditional-complexity": false,
    "template-cyclomatic-complexity": false,
    "template-no-call-expression": false,
    "template-use-track-by-function": false,
    "trackBy-function": false,
    "use-view-encapsulation": false,
    // many more rules ...
  }
}
```

_Edit_ : fix spelling of rule name from `template-no-call-expressssion` to `template-no-call-expression`. Even with the corrected name, still having the same problem.

**Comment by rafaelss95** [comment] 2019-06-10 02:41
Duplicate of #821.

**Closed by rafaelss95** 2019-06-10 02:41 UTC
