### ISSUE TITLE
no-access-missing-member does not find members in base classes

### ISSUE THREAD

**Issue by kevinphelps** [mgechev/codelyzer#383] opened 2017-07-23 01:29 UTC
Using `myMethod` from the `BaseComponent` class in the `MyComponent` template will result in an error.

`The method "myMethod" that you're trying to access does not exist in the class declaration.`

```typescript
// base.component.ts
export class BaseComponent {
  someMethod() { }
}
```

```typescript
// my.component.ts
@Component({
  selector: 'app-my-component',
  templateUrl: './my.component.html'
})
export class MyComponent extends BaseComponent {
  constructor() {
    super();
  }
}
```

```html
<!--my.component.html -->
<button (click)="myMethod()"></button>
```

**Comment by wKoza** [comment] 2017-07-23 05:39
duplicate of #361

**Closed by wKoza** 2017-07-23 05:39 UTC
