### ISSUE TITLE
fix of rule whitespace in interpolation breaks html

### ISSUE THREAD

**Issue by victornoel** [mgechev/codelyzer#541] opened 2018-03-12 08:08 UTC
I'm using tslint-angular and the following was wrongly fixed

From:
```html
<div class="legend">
  &nbsp;{{legend}}
</div>
```

To:
```html
<div class="legend">
  &{{ sp;{{l }}end}}
</div>
```

I'm not sure which rule is used exactly though…

**Comment by mgechev** [comment] 2018-03-12 16:59
Duplicate of https://github.com/mgechev/codelyzer/issues/526.

We'll temporarily disable auto fixes in the next release.

**Closed by mgechev** 2018-03-12 16:59 UTC
