### ISSUE TITLE
Build fails at the end after running tslint from command line

### ISSUE THREAD

**Issue by xtianus79** [mgechev/codelyzer#144] opened 2016-11-09 21:55 UTC
the error is completely generic but it is Exit Status 2:

The command I am using to run is this. 
    `"lint":` "tslint \"src/**/*.ts\"",`

`0 info it worked if it ends with ok
1 verbose cli [ '/Users/mbp06/.nvm/versions/node/v6.2.2/bin/node',
1 verbose cli   '/Users/mbp06/.nvm/versions/node/v6.2.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@3.9.5
3 info using node@v6.2.2
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle my-application@1.0.0~prelint: my-application@1.0.0
6 silly lifecycle my-application@1.0.0~prelint: no script for prelint, continuing
7 info lifecycle my-application@1.0.0~lint: my-application@1.0.0
8 verbose lifecycle vmya-application@1.0.0~lint: unsafe-perm in lifecycle true
9 verbose lifecycle my-application@1.0.0~lint: PATH: /Users/mbp06/.nvm/versions/node/v6.2.2/lib/node_modules/npm/bin/node-gyp-bin:/Users/mbp06/Repos/propertymarketing/frontend/node_modules/.bin:/Users/mbp06/.nvm/versions/node/v6.2.2/bin:/Users/mbp06/.dnx/runtimes/dnx-mono.1.0.0-rc1-update1/bin:/Users/my/.dnx/bin:/Users/mbp06/.nvm/versions/node/v6.2.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/bin:/Users/my/Library/Android/sdk/tools:/Users/bcr05/Library/Android/sdk/platform-tools
10 verbose lifecycle my-application@1.0.0~lint: CWD: /Users/my/my/my/my
11 silly lifecycle my-application@1.0.0~lint: Args: [ '-c', 'tslint "src/**/*.ts"' ]
12 silly lifecycle my-application@1.0.0~lint: Returned: code: 2  signal: null
13 info lifecycle my-application@1.0.0~lint: Failed to exec lint script
14 verbose stack Error: my-application@1.0.0 lint: `tslint "src/**/*.ts"`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/Users/mbp06/.nvm/versions/node/v6.2.2/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/mbp06/.nvm/versions/node/v6.2.2/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid vca-application@1.0.0
16 verbose cwd /Users/mbp06/Repos/propertymarketing/frontend
17 error Darwin 14.5.0
18 error argv "/Users/mbp06/.nvm/versions/node/v6.2.2/bin/node" "/Users/mbp06/.nvm/versions/node/v6.2.2/bin/npm" "run" "lint"
19 error node v6.2.2
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error vca-application@1.0.0 lint: `tslint "src/**/*.ts"`
22 error Exit status 2
23 error Failed at the vca-application@1.0.0 lint script 'tslint "src/**/*.ts"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the my-application package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tslint "src/**/*.ts"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs my-application
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls my-application
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

I can't figure out what is going wrong with this

**Comment by mgechev** [comment] 2016-11-09 22:10
Would you try  `npm i -g tslint` and `tslint "src/**/*.ts"`?

Right after that change `tslint.json` and drop all codelyzer rules. This way we can see if the problem is here.

**Comment by xtianus79** [comment] 2016-11-10 15:54
@mgechev Ok... I have figured out that if there is an error and it returns something then the error is thrown... if nothing is wrong then i proceeds to check and return nothing but a new console line.

**Comment by xtianus79** [comment] 2016-11-10 16:09
here is my tsling.json

````
{
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
  "rules": {
    "class-name": true,
    "comment-format": [
      true,
      "check-space"
    ],
    "curly": true,
    "eofline": true,
    "forin": true,
    "indent": [
      true,
      "spaces"
    ],
    "label-position": true,
    "max-line-length": [
      true,
      140
    ],
    "member-access": false,
    "member-ordering": [
      true,
      "static-before-instance",
      "variables-before-functions"
    ],
    "no-arg": true,
    "no-bitwise": true,
    "no-console": [
      true,
      "debug",
      "info",
      "time",
      "timeEnd",
      "trace"
    ],
    "no-construct": true,
    "no-debugger": true,
    "no-duplicate-variable": true,
    "no-empty": false,
    "no-eval": true,
    "no-inferrable-types": true,
    "no-shadowed-variable": true,
    "no-string-literal": false,
    "no-switch-case-fall-through": true,
    "no-trailing-whitespace": true,
    "no-unused-expression": true,
    "no-unreachable": true,
    "no-use-before-declare": true,
    "no-var-keyword": true,
    "object-literal-sort-keys": false,
    "one-line": [
      true,
      "check-open-brace",
      "check-catch",
      "check-else",
      "check-whitespace"
    ],
    "quotemark": [
      true,
      "single"
    ],
    "radix": true,
    "semicolon": [
        true,
      "always"
    ],
    "triple-equals": [
      true,
      "allow-null-check"
    ],
    "typedef-whitespace": [
      true,
      {
        "call-signature": "nospace",
        "index-signature": "nospace",
        "parameter": "nospace",
        "property-declaration": "nospace",
        "variable-declaration": "nospace"
      }
    ],
    "variable-name": false,
    "whitespace": [
      true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-separator",
      "check-type"
    ],

    "directive-selector-name": [true, "camelCase"],
    "component-selector-name": [true, "kebab-case"],
    "directive-selector-type": [true, "attribute"],
    "component-selector-type": [true, "element"],
    "directive-selector-prefix": [true, "sg"],
    "component-selector-prefix": [true, "sg"],
    "use-input-property-decorator": true,
    "use-output-property-decorator": true,
    "use-host-property-decorator": true,
    "no-attribute-parameter-decorator": true,
    "no-input-rename": true,
    "no-output-rename": true,
    "no-forward-ref": true,
    "use-life-cycle-interface": true,
    "use-pipe-transform-interface": true,
    "pipe-naming": [true, "camelCase", "sg"],
    "component-class-suffix": true,
    "directive-class-suffix": true,
    "import-destructuring-spacing": true,
    "templates-use-public": true,
    "no-access-missing-member": true,
    "invoke-injectable": true
  }
}
````

**Comment by mgechev** [comment] 2016-11-13 01:54
@xtianus79 what's your TypeScript version? Might be related to https://github.com/mgechev/codelyzer/issues/145.

**Comment by xtianus79** [comment] 2016-11-16 21:05
@mgechev typescript ^2.1

**Comment by mgechev** [comment] 2016-12-02 21:13
@xtianus79 would you try with the latest version? It's 2.0.0-beta.1.

**Comment by mgechev** [comment] 2016-12-10 17:22
I'm closing it for now, found an issue in the `SyntaxKind` definition. I'll push the changes in beta.2.

Ref: https://github.com/mgechev/codelyzer/commit/20ce61a64346b9ac17a1d5d5f364889ef90e6d47

**Closed by mgechev** 2016-12-10 17:22 UTC
