### ISSUE TITLE
Incorrect formatting with check-interpolation

### ISSUE THREAD

**Issue by mgechev** [mgechev/codelyzer#487] opened 2018-01-10 13:11 UTC
@dereklin:

> When I run npm run lint -- --fix
> This
> ```
> <h1>
>   {{name}}
> </h1>
> ```
> is turned into this:
> ```
> <h1>
>  {{ {nam }}}
> </h1>
> ```
> Here is my repo: https://github.com/dereklin/nx-demo-jest/tree/try-tslint-config
> The template is at: https://github.com/dereklin/nx-demo-jest/blob/try-tslint-config/apps/app1/src/app/feature1/feature1.component.html

https://github.com/mgechev/tslint-angular/issues/1

**Comment by wKoza** [comment] 2018-01-10 20:40
Duplicate #452 ?

**Comment by mgechev** [comment] 2018-01-16 18:41
Here we have a broken auto fix.

**Comment by mgechev** [comment] 2018-01-16 19:06
I cannot reproduce this issue https://github.com/mgechev/codelyzer/pull/494

**Comment by wKoza** [comment] 2018-01-16 19:28
What's your OS @dereklin ?

**Comment by wKoza** [comment] 2018-01-16 19:41
I took a closer look at this problem.  It's the same sort of problem that #452 . It may be a problem of carriage return. I've never been able to catch it with a TU.

**Comment by mgechev** [comment] 2018-01-16 20:15
@wKoza I thought it might be OS related but we run tests in Windows as well.

**Comment by dereklin** [comment] 2018-01-16 20:48
@wKoza It's Windows 10.  I encountered the problem when I was trying out tslint-angular.

**Comment by wKoza** [comment] 2018-01-17 06:48
I will test with my PC at work. But, if I remember correctly, This problem is not catchable with a TU currently .

**Comment by wKoza** [comment] 2018-01-17 10:19
I tested  with Windows. I  reproduce the problem with Webstrom. 

![img1](https://image.ibb.co/c5z8sR/Capture1.png)

![img2](https://image.ibb.co/daFsK6/Capture2.png)

When I change the file encoding to LF instead of CRLF, it's work:

![img3](https://image.ibb.co/bs53Rm/Capture3.png)

I'll search a fix ...

**Comment by mgechev** [comment] 2018-01-17 14:44
Thanks for looking into it!

**Comment by wKoza** [comment] 2018-01-18 17:51
Correct this issue isn't easy. In this case, the problem happens when the corrected string  is injected into the file with Tslint. There is a lag between `\n` et `\r\n`.

**Comment by mgechev** [comment] 2018-02-11 20:04
Will move this issue to a future release.

**Comment by agrinko** [comment] 2018-11-01 20:48
I can add another case to this issue.
Angular-whitespace autofix breaks my component in the following piece of template:
```
  <span *ngSwitchCase="'interval'">
    [Period: {{ body.content.period.value.start }} &#8594; {{body.content.period.value.end}}]
  </span>
```
It replaced it like this:
```
  <span *ngSwitchCase="'interval'">
    [Period: {{ body.content.period.value.start }} &#{{ 94; {{body.content.period.val }}.end}}]
  </span>
```
Luckily Angular reported error and I could notice it and fix.
I'm using Ubuntu, and I don't think it depends on OS. Looks like some flaws in the algorithm or regexp.

**Comment by wKoza** [comment] 2018-11-02 08:03
@agrinko , your error isn't in relation to your OS;  It's the same problem that this issue #579.

**Comment by wKoza** [comment] 2018-11-26 08:48
Since `angular-whitespace` is now deprecated, we can close this issue.

**Closed by wKoza** 2018-11-26 08:48 UTC
Labels: bug
