### ISSUE TITLE
[Feature Request] - Do not allow EventEmitter in Service

### ISSUE THREAD

**Issue by rafaelss95** [mgechev/codelyzer#457] opened 2017-11-16 22:40 UTC
The [docs](https://angular.io/api/core/EventEmitter) about `EventEmitter` says:

> Use by directives and components to emit custom Events.

Although there's nothing explicit saying that we SHOULDN'T use EventEmitter in a Service, [this excellent answer on SO](https://stackoverflow.com/questions/36076700/what-is-the-proper-use-of-an-eventemitter#answer-36076701) clarify things a bit more: 

> Angular2 will never guarantee us that EventEmitter will continue being an Observable. So that means refactoring our code if it changes. The only API we must access is its emit() method. We should never subscribe manually to an EventEmitter.

<hr>

Example:

```
class MyService {
  // Ok, here we are using @Output, so this can be handled by not-allowed-decorator rule (in future)?
  @Output() myEvent = new EventEmitter<any>(); 
  myEvent = new EventEmitter<any>();
}

@Component({
  selector : 'app-root'
  // ...
})
class AppComponent implements OnInit {
  constructor(private myService: MyService) { }

  ngOnInit() {
    this.myService.myEvent.emit();

    this.myService.myEvent.subscribe(() => console.log('x'));
  }
}
```

**Comment by mgechev** [comment] 2017-11-25 20:02
@rafaelss95 sounds good. Will be great if you can open a PR with this rule!

**Comment by mgechev** [comment] 2018-01-07 17:26
@rafaelss95 there's something which makes this rule not trivial to implement. We can easily verify if the value of given property equals `new EventEmitter` and throw a warning. The problem is that without type checking we cannot easily verify that `EventEmitter` is actually imported from `@angular/core` or, let's say, `const EventEmitter = require('event-emitter');`

**Comment by wKoza** [comment] 2018-01-08 12:14
I'm also implementing this rule and I come to the same conclusion ;) 

@mgechev , have you an idea for testing this code ? 

```
this.myService.myEvent.subscribe(() => console.log('x'));
```

**Comment by mgechev** [comment] 2018-01-08 12:21
@wKoza using type checking is still an option but the rule won't be used by editors like VSCode, for instance.

**Comment by wKoza** [comment] 2018-01-08 13:46
Maybe, is it the time to provide two tools : one for the shallow analysis and an other for a deep analysis. We have some features in this way.

**Comment by mgechev** [comment] 2018-01-08 13:53
That's true, the only issue would be that at first the tool which performs deep analysis won't have editor/IDE support.

**Comment by wKoza** [comment] 2018-01-08 20:45
I will take a look at this. Do you already have tested it ?

**Comment by mgechev** [comment] 2018-01-09 08:34
It's used [here](https://github.com/mgechev/ngast/blob/master/lib/project-symbols.ts#L29). Mostly for [creating a program](https://github.com/mgechev/ngast/blob/master/lib/project-symbols.ts#L79). Still needs to be used together with `@angular/compiler` & `@angular/compiler-cli`.

**Comment by mgechev** [comment] 2018-05-02 17:40
Following the feature request process that [lodash has](https://github.com/lodash/lodash/blob/master/.github/CONTRIBUTING.md#feature-requests), I'm closing the issue and adding `votes needed` label.

Later we can prioritize the feature requests by popularity and include them in a future release.

**Closed by mgechev** 2018-05-02 17:40 UTC
Labels: enhancement, votes needed

**Comment by Nexeuz** [comment] 2018-07-27 23:53
+1

**Comment by mgechev** [comment] 2018-07-28 00:11
@Nexeuz you can hit 👍 on @rafaelss95's comment. `+1` will not be reflected in the [voting process](https://github.com/mgechev/codelyzer/blob/master/CONTRIBUTING.md#-missing-a-feature).
