### ISSUE TITLE
Cannot find module 'tslint\lib\lint'

### ISSUE THREAD

**Issue by negberts** [mgechev/codelyzer#161] opened 2016-11-22 08:30 UTC
Upgraded tslint to 4.0.1 and gulp-tslint to 7.0.1. 

Codelyzer gives the error mentioned in the title in file selectorNameBase.js

var Lint = require("tslint/lib/lint");

**Comment by 4kochi** [comment] 2016-11-22 09:53
Tslint 4.0 API has changed:

https://github.com/palantir/tslint/pull/1720

**Comment by devoto13** [comment] 2016-11-22 10:20
I think it can be closed as duplicate of #157.

**Closed** 2016-11-22 10:22 UTC

**Comment by mgechev** [comment] 2016-11-28 01:45
You can now use `2.0.0-beta.1` which works with tslint 4.

**Comment by SatishMHiremath** [comment] 2018-03-06 07:04
Codelyzer

A set of tslint rules for static code analysis of Angular TypeScript projects.

You can run the static code analyzer over web apps, NativeScript, Ionic, etc.

Angular CLI has support for codelyzer.Run the below npm command for tslint

npm i tslint-angular
